### PR TITLE
feat: add default mac menu bar items

### LINKED ISSUE #83: Feature Request: Support for macOS Keyboard Shortcuts (e.g., Cmd+M for minimizing)
Would be nice if we could minimize BudgetBudget the usual way, i.e., by pressing Cmd+M, like virtually every other macOS App out there :)

### PR DESCRIPTION
**Pull request by leo-benz**
- Add default 'Window' menu
- Add help menu with links to github issues and wiki

Closes #83

### CODE REVIEW

**Comment by Xiphe** [comment]
Cool! Thanks for the PR.

(And also sorry for not really working on this lately :/)

**Comment by Xiphe** [comment]
the release did not went through :/

Will look into that within the next days

**Comment by leo-benz** [comment]
I checked the build log and noticed that I faced the same issue locally when packaging a build. I traced it down to an incompatibility between ts-loader and webpack (see https://github.com/TypeStrong/ts-loader/issues/595). By updating CRA to the next version (see https://github.com/facebook/create-react-app/discussions/11278) it was fixed. I did not commit these changes because I thought it is a local issue and I don't know if updating CRA has any side effects.

**Comment by Xiphe** [comment]
Ah awesome! Thanks for sharing. Will try that later today

**Pull request merged**
